booking_app/urls.py
from .import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),
    path('appointments/', views.ViewAppointments.as_view(), name='appointments'),
    path('delete/<int:appointment_id>', views.delete_appointment, name='delete'),
    path('edit/<int:appointment_id>', views.edit_appointment, name='edit'),
]

home_learning_hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include('booking_app.urls'), name="booking-urls"),
    path('resources_app/', include('resources_app.urls'), name="resources-urls"),
    path('accounts/', include('allauth.urls')),
]

resources_app/urls.py
from .import views
from django.urls import path


urlpatterns = [
    path('resources/', views.DisplayResource.as_view(), name='resources'),
    path('edit_resources/', views.uploadResource, name='edit_resources')
]

booking_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone
from cloudinary.models import CloudinaryField

# Custom choices
APPOINTMENT_TIMES = (
    ('0', '15:00 - 15:15'),
    ('1', '15:15 - 15:30'),
    ('2', '15:30 - 15:45'),
    ('3', '15:45 - 16:00'),
    ('4', '16:00 - 16:15'),
    ('5', '16:15 - 16:30'),
    ('6', '16:30 - 16:45'),
)

TEACHERS = (
    ('0', 'Mr Oakley'),
    ('1', 'Mrs Brundle'),
    ('2', 'Mr Simons'),
    ('3', 'Miss Baxter'),
    ('4', 'Mrs Shepard'),
    ('5', 'Miss Edwards'),
)


# Date validator to stop past dates being selected
def validate_date(date):
    if date < timezone.now().date():
        raise ValidationError("Date cannot be in the past")


# Appointments class for users to book an appointment slot
class Appointment(models.Model):
    parent_name = models.CharField(max_length=80)
    child_name = models.CharField(max_length=80)
    teacher_name = models.CharField(
        max_length=80, choices=TEACHERS, default='0')
    date = models.DateField(validators=[validate_date])
    time = models.CharField(
        max_length=50, choices=APPOINTMENT_TIMES, default='0')
    comment = models.TextField(default=None)

    class Meta:
        unique_together = ["teacher_name", "date", "time"]

    def __str__(self):
        return f"{self.date} | {self.parent_name} | {self.child_name}"

resources_app/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Custom choices
SUBJECTS = (
    ('0', 'English'),
    ('1', 'Maths'),
    ('2', 'History'),
    ('3', 'Geography'),
    ('4', 'Art'),
    ('5', 'Science'),
    ('6', 'Music'),
)


# Resource class for admins to upload a resource to library
class Resource(models.Model):
    resource_name = models.CharField(max_length=80)
    subject = models.CharField(
        max_length=80, choices=SUBJECTS, default='0')
    description = models.CharField(max_length=150)
    file = CloudinaryField(resource_type='raw', blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

booking_app/forms.py
from .models import Appointment
from django import forms
from django.forms import ModelForm
from django.core.exceptions import NON_FIELD_ERRORS


# Date selector
class DateInput(forms.DateInput):
    input_type = 'date'


# Appointment form
class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'
        widgets = {
            'date': DateInput(),
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Please select another time and date\
                    combination and try again.",
            }
        }

resources_app/forms.py
from .models import Resource
from django import forms
from django.forms import ModelForm


# Resource upload form
class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resource
        fields = '__all__'

booking_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from .models import Appointment
from .forms import AppointmentForm
from django.contrib import messages
from django.urls import reverse


# Render index.html and appointment form
def index(request):
    form = AppointmentForm()
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            human = True
            messages.success(request, f"Thanks for making an appointment, your\
                child's teacher will email you soon to confirm.")
            return redirect('index')
        else:
            messages.error(request, f"There was an error submitting your\
                appointment. Please try a different date/time.")
    return render(request, 'index.html', {'form': form})


# Render appointment cards in appointments.html
class ViewAppointments(generic.ListView):
    model = Appointment
    queryset = Appointment.objects.all().order_by('-date')
    template_name = 'appointments.html'
    context_object_name = 'appointment_items'
    paginate_by = 6


# Delete an appointment
def delete_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    appointment.delete()
    messages.add_message(request, messages.SUCCESS, f"Appointment successfully\
        deleted!")
    return redirect('appointments')


# Edit an appointment
def edit_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        form = AppointmentForm(request.POST, instance=appointment)
        if form.is_valid():
            form.save()
            return redirect('appointments')
    form = AppointmentForm(instance=appointment)
    context = {
        'form': form
    }
    return render(request, 'edit_appointment.html', context)

resources_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from .models import Resource
from .forms import ResourceForm
from django.contrib import messages
from django.urls import reverse


# Render resources for all users
class DisplayResource(generic.ListView):
    model = Resource
    queryset = Resource.objects.all().order_by('-created_on')
    template_name = 'resources.html'
    context_object_name = 'resource_items'
    paginate_by = 9


# Allow admin to upload resources and display them
def uploadResource(request):
    form = ResourceForm()
    if request.method == 'POST':
        form = ResourceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            human = True
            messages.success(request, f"Resource uploaded successfully!")
            return redirect('edit_resources')
        else:
            messages.error(request, f"Error: Could not upload file.")
    return render(request, 'edit_resources.html', {'form': form})

templates/appointments.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Appointments header -->
<div class="col-12 text-center mt-2 mb-2">
    <h1 class="mb-2 text-center page-header">Appointments</h1>
</div>

<!-- Appointments container -->
<div class="container-fluid">
    <div class="row justify-content-center">
        {% for appointment in appointment_items %}
        <div class="col-md-3 appointment-card">
            <h3><strong>{{ appointment.get_teacher_name_display }}</strong></h3>

            <h4><strong>Parent:</strong> {{ appointment.parent_name }} | <strong>Pupil:</strong>
                {{ appointment.child_name }}</h4>

            <p><strong>Date:</strong> {{ appointment.date }} | <strong>Time:</strong>
                {{ appointment.get_time_display }}</p>

            <p class="appointment-note">{{ appointment.comment|safe }}</p>

            <!-- Edit button -->
            <a href="/edit/{{ appointment.id }}" class="btn btn-primary">Edit</a>

            <!-- Delete button -->
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalDelete">
                Delete
            </button>

            <!-- Delete modal -->
            <div id="modalDelete" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Delete Appointment</h5>
                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>You are about to delete this appointment.</p>
                            <p>This action cannot be undone. Do you wish to continue?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary modal-btn" data-bs-dismiss="modal">Go
                                back</button>
                            <a href="{% url 'delete' appointment.id %}" class="btn btn-danger modal-btn">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor%}
    </div>
</div>

<!-- Pagination -->
{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-lg submitBtn">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-lg submitBtn"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{%endblock%}

templates/base.html
{% load static %}
{% load active_link_tags %}

<!DOCTYPE html>
<html class="h-100" lang="eng">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="The Learning Hub - a space for parents and schools to connect">
    <meta name="keywords" content="school, appointment, parent-teacher, The Learning Hub">
    <meta name="author" content="Nick Coles">
    <title>The Learning Hub</title>
    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&family=Schoolbell&display=swap" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- CSS stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">

</head>

<body class="d-flex flex-column h-100">
    <!-- Naviagtion -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand hub-logo" href="{% url 'index' %}">The Learning Hub</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% active_link 'index' strict=True %}" aria-current="page"
                            href="{% url 'index' %}">Home</a>
                    </li>
                    <!-- Checks if user is admin -->
                    {% if user.is_authenticated %}
                    <!-- Appointments nav link -->
                    <li class="nav-item">
                        <a class="nav-link {% active_link 'appointments' strict=True %}"
                            href="{% url 'appointments' %}">Appointments</a>
                    </li>
                    <!-- Upload resources nav link -->
                    <li class="nav-item">
                        <a class="nav-link {% active_link 'edit_resources' strict=True %}"
                            href="{% url 'edit_resources' %}">Upload Resources</a>
                    </li>
                    <!-- Logout nav link -->
                    <li class="nav-item">
                        <a class="nav-link" role="button" data-bs-toggle="modal"
                            data-bs-target="#modalLogout">Logout</a>
                        <!-- Logout modal -->
                        <div id="modalLogout" class="modal fade" tabindex="-1" data-backdrop="static"
                            data-keyboard="false" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Logout</h5>
                                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>You are about to logout from your account.</p>
                                        <p>Are you sure you wish to continue?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger modal-btn"
                                            data-bs-dismiss="modal">No</button>
                                        <a href="{% url 'account_logout' %}" class="btn btn-success modal-btn">Yes - Log
                                            me out!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <!-- Provide further nav links to unauthorised user -->
                    {% else %}
                    <!-- Resource Library nav link -->
                    <li class="nav-item">
                        <a class="nav-link {% active_link 'resources' strict=True %}"
                            href="{% url 'resources' %}">Resource Library</a>
                    </li>
                    <!-- Login nav link -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    "The parent-teacher connection"
                </span>
            </div>
        </div>
    </nav>
    <!-- Message alerts-->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                    </button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Main page template content -->
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Template content -->
        {% endblock content %}
    </main>
    <!-- Footer -->
    <footer class="footer mt-auto py-1 footer-container">
        <div class="row justify-content-md-center">
            <div class="col col-lg-2 text-center">
                <p class="mt-3">Website created by Nick Coles <a href="https://github.com/NickdevC"><i
                            class="fa-brands fa-github"></i></a>
                    <a href="https://www.linkedin.com/in/nick-coles-78a33b184/"><i
                            class="fa-brands fa-linkedin"></i></a></p>
            </div>
            <div class="col col-lg-2 text-center">
                <p class="mt-3">For educational purposes only</p>
            </div>
        </div>
    </footer>

    <!-- Bootstrap script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <!-- Font awesome -->
    <script src="https://kit.fontawesome.com/2c38219dd7.js" crossorigin="anonymous"></script>
    <!-- Message handler timer -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>
</body>

</html>

templates/edit_appointment.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Header -->
<div class="col-12 text-center mt-3 mb-3">
    <h1 class="text-center page-header">Edit Appointment</h1>
</div>

<!-- Container and form -->
<div class="container-fluid">
    <div class="row">
        {% if user.is_authenticated %}
        <div class="row m-2 row d-flex justify-content-center">
            <div class="col-md-6 mb-4 text-center appointment-card content-card">
                <!-- Form for editing the appointment model -->
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-signup btn-lg submitBtn">Update appointment</button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{%endblock%}

templates/edit_resources.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Header -->
<div class="col-12 text-center mt-3 mb-3">
    <h1 class="text-center page-header">Upload a resource:</h1>
</div>

<!-- Container and form -->
<div class="container-fluid">
    <div class="row">
        {% if user.is_authenticated %}
        <div class="row m-2 row d-flex justify-content-center">
            <div class="col-md-6 mb-4 text-center appointment-card content-card">
                <!-- Form for uploading a resource to resources.html -->
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-signup btn-lg submitBtn">Upload</button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Hero container -->
<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <!-- Hero image (aligned right) -->
        <div class="col-10 col-sm-8 col-lg-6">
            <img src="https://res.cloudinary.com/nickdevc/image/upload/v1677073708/media/communication_nle8ql.png"
                class="d-block mx-lg-auto img-fluid hero-image" alt="Communicating learning cartoon" width="700"
                height="500" loading="lazy">
        </div>
        <!-- Hero text (aligned left) -->
        <div class="col-lg-6">
            <h1 class="display-5">Welcome to The Learning Hub!</h1>
            <p class="lead">Here we hope to grow parent-teacher connections by allowing swift,
                hassel-free communication via our appointment booking system. You will also find our extensive
                resource library will support you and your child by providing resources that have been 'hand-picked'
                by your child's school.
            </p>
            <p class="lead"><i class="fa-solid fa-arrow-down"></i> Scroll down to book an appointment with a teacher <i
                    class="fa-solid fa-arrow-down"></i></p>
            <div class="d-grid gap-2 d-md-flex justify-content-center">
                <a href="{% url 'resources' %}" class="btn btn-signup btn-lg submitBtn">In need of resources?</a>
            </div>
        </div>
    </div>
</div>
<hr class="line-break">
<!-- User appointment container and form -->
<div class="container-fluid px-1 py-5 mx-auto">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-5 col-lg-5 col-md-9 col-11 text-center">
            <h1>
                Book an appointment
            </h1>
            <h2>Use the form below to book an appointment with your child's teacher</h2>
            <div class="appointmentcard">
                <form method="post" id="appointmentForm">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg submitBtn">Submit &raquo;</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/resources.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Hero container -->
<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <!-- Hero image (aligned right) -->
        <div class="col-10 col-sm-8 col-lg-6">
            <img src="https://res.cloudinary.com/nickdevc/image/upload/v1677073708/media/resources_d4da1d.png"
                class="d-block mx-lg-auto img-fluid hero-image" alt="Children learning cartoon" width="700" height="500"
                loading="lazy">
        </div>
        <div class="col-lg-6">
            <h1 class="display-5">The Resource Library</h1>
            <p class="lead">Here you will find a range of resources that have been selected to match your
                child's study within the classroom. Teachers will regularly update the library with new
                exciting resources for you to use at home to reinforce learning and boost confidence.
            </p>
        </div>
    </div>
</div>
<hr class="line-break">
<div class="col-12 text-center mt-3 mb-3">
    <h1 class="mb-4 text-center page-header">Current Resources</h1>
</div>
<div class="container-fluid">
    <div class="row justify-content-center">
        {% for resource in resource_items %}
        <div class="col-xl-2 col-md-3 col-sm-4 appointment-card">
            <h3 class="resource-name">{{ resource.resource_name }}</h3>

            <h4 class="resource-subject">Subject: <strong>{{ resource.get_subject_display }}</strong></h4>

            <p class="resource-description">{{ resource.description }}</p>
            <div class="d-grid gap-2 col-4 mx-auto">
                <a href="{{ resource.file.url }}" target="_blank"
                    class="resource-link btn btn-signup btn-sm submitBtn">Download</a>
            </div>
        </div>
        {% endfor%}
    </div>
</div>

{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock %}